server:
  port: 7986

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffectedRows=true&useSSL=false
    username: root
    password: Mxredu@2020

  servlet:
    multipart:
      max-file-size: 1Mb
      max-request-size: 1Mb

  thymeleaf:
    cache: false
    prefix: classpath:/templates
    resources:
      static-locations: classpath:templates,classpath:static


mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml


